#!/bin/sh

if ! command -v stylua >/dev/null 2>&1; then
  echo "StyLua is not installed."
  exit 1
fi

staged_lua_files=$(git diff --cached --name-only --diff-filter=ACM | grep '\.lua$')

if [ -n "$staged_lua_files" ]; then
  failed=0
  echo "Formatted Files"
  echo "$staged_lua_files" | while IFS= read -r file; do
    if [ -f "$file" ]; then
      stylua "$file"
      if [ $? -eq 0 ]; then
        git add "$file"
        echo " - $file"
      else
        failed=1
        echo " - $file (failed)"
      fi
    fi
  done
  if [ $failed -ne 0 ]; then
    exit 1
  fi
fi
